name: C/C++ CI

on: [push, pull_request]

jobs:
  build-linux:
    name: Linux build

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y libkrb5-dev
    - name: configure
      run: |
        ./bootstrap
        ./configure
    - name: make
      run: make
    - name: make distcheck
      run: make distcheck

  build-windows:
    name: Windows build

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - name: Cmake configure
      run: |
        cmake -G "Visual Studio 17 2022" .
    - name: Build (MSVC)
      run: |
        cmake --build .

  build-ps2-ee:
    name: PS2 build

    runs-on: ubuntu-latest
    container: ps2dev/ps2dev:latest
    steps:
    - name: Install dependencies
      run: |
        apk add build-base git zip gawk python3 py3-pip bash

    - name: git checkout
      uses: actions/checkout@v3

    - name: Compile PS2 EE Side
      run: |
        cd lib
        make -f Makefile.PS2 clean
        make -f Makefile.PS2 all_ee

    - name: Compile PS2 IOP Side
      run: |
        cd lib
        make -f Makefile.PS2 clean
        make -f Makefile.PS2 all_iop

  build-ps3-ppu:
    name: PS3 PPU build

    runs-on: ubuntu-20.04
    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Set env vars
      id: slug
      run: |
        echo "sha_name=$(echo ${GITHUB_SHA} | cut -c1-8)" >> $GITHUB_ENV
      # using pre-compiled sdk
    - name: Download PSL1GHT Toolchain
      run: |
        curl -sL https://github.com/bucanero/ps3toolchain/releases/download/ubuntu-latest-fad3b5fb/ps3dev-ubuntu-latest-2020-08-31.tar.gz | tar xvz -C ./
        echo "PS3DEV=${GITHUB_WORKSPACE}/ps3dev" >> $GITHUB_ENV
        echo "PSL1GHT=${GITHUB_WORKSPACE}/ps3dev" >> $GITHUB_ENV
    - name: build libsmb2
      run: |
        cd lib
        make -f Makefile.PS3_PPU clean
        make -f Makefile.PS3_PPU
